apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - private-web
  routes:
    - match: Host(`grafana.warrenlayson.xyz`)
      kind: Rule
      services:
      - name: grafana
        namespace: monitoring
        port: 80
