apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.warrenlayson.xyz`)
      kind: Rule
      services:
      - name: grafana
        port: 80
  tls:
    secretName: warrenlayson-xyz-tls
