apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - ingressroute.yaml
configMapGenerator:
  - name: grafana-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
