apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: actualbudget
  namespace: actualbudget
spec:
  entryPoints:
    - private-web
  routes:
    - match: Host(`actualbudget.warrenlayson.xyz`)
      kind: Rule
      services:
      - name: actualbudget
        port: 5006
