---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actual
  namespace: flux-system
spec:
  chart:
    spec:
      chart: actualbudget
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: community-charts
  interval: 50m0s
  values:
    persistence:
      enabled: true
