---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h0m0s
  url: https://traefik.github.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 12h
  chart: traefik
  sourceRef:
    kind: HelmRepository
    name: traefik
  version: '35.*'
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-crds
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik-crds
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  interval: 30m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-internal
  namespace: traefik
spec:
  chartRef:
    kind: HelmChart
    name: traefik
    namespace: traefik
  interval: 30m
  install:
    crds: Skip
  upgrade:
    crds: Skip
  valuesFrom:
  - kind: ConfigMap
    name: traefik-values
  values:
    providers:
      kubernetesCRD:
        ingressClass: traefik-internal

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-external
  namespace: traefik
spec:
  chartRef:
    kind: HelmChart
    name: traefik
    namespace: traefik
  interval: 30m
  install:
    crds: Skip
  upgrade:
    crds: Skip
  valuesFrom:
  - kind: ConfigMap
    name: traefik-values
  values:
    providers:
      kubernetesCRD:
        ingressClass: traefik-external

