apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - common.yml
configMapGenerator:
  - name: traefik-values
    namespace: traefik
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yml
