ingressClass:
  name: traefik
providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: false
service:
  enabled: true
  type: LoadBalancer
  loadBalancerIP: "192.168.0.241"
  additionalServices:
    cluster:
      type: ClusterIP
      labels:
        traefik-service-label: internal
      specs:
        ports:
          - port: 80
            name: web
            targetPort: web
          - port: 443
            name: websecure
            targetPort: websecure
    lb:
      type: LoadBalancer
      labels:
        traefik-service-label: internal
      specs:
        loadBalancerIP: "192.168.0.240"
        ports:
        - port: 80
          name: web
          targetPort: web
        - port: 443
          name: websecure
          targetPort: websecure


rbac:
  enabled: true

ingressRoute:
  dashboard:
    enabled: false

ports:
  traefik:
    expose:
      default: false
      internal: true
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true

tlsStore:
  default:
    defaultCertificate:
      secretName: warrenlayson-xyz-tls
