---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h0m0s
  url: https://traefik.github.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 12h
  chart: traefik
  reconcileVersion: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: traefik
  version: '35.*'
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-external
  namespace: traefik
spec:
  chartRef:
    kind: HelmChart
    name: traefik
    namespace: traefik
  interval: 12h0m0s
  values:
    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=DEBUG"
    ingressRoute:
      dashboard:
        enabled: false
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        tls:
          enabled: true
      rbac:
        enabled: true
      providers:
        kubernetesCRD:
          enabled: true
          ingressClass: traefik-external
        kubernetesIngress:
          enabled: true
          publishedService:
            enabled: false
      service:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "192.168.0.81"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-internal
  namespace: traefik
spec:
  chartRef:
    kind: HelmChart
    name: traefik
    namespace: traefik
  interval: 12h0m0s
  values:
    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=DEBUG"
    ingressRoute:
      dashboard:
        enabled: false
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        tls:
          enabled: true
      rbac:
        enabled: true
      providers:
        kubernetesCRD:
          enabled: true
          ingressClass: traefik-internal
        kubernetesIngress:
          enabled: true
          publishedService:
            enabled: false
      service:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "192.168.0.80"
