---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h0m0s
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  interval: 12h0m0s
  values:
    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=DEBUG"
    ingressRoute:
      dashboard:
        enabled: false
    ports:
      http:
        redirectTo:
          port: https
          permanent: true
          priority: 10
      https:
        tls:
          enabled: true
      http-external:
        redirectTo:
          port: https-external
          permanent: true
          priority: 10
      https-external:
        tls:
          enabled: true
      rbac:
        enabled: true
      providers:
        kubernetesCRD:
          enabled: true
        kubernetesIngress:
          enabled: true
          publishedService:
            enabled: false
      service:
        enabled: true
        type: LoadBalancer
