
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: vault-secrets-operator-system
spec: {}
status: {}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: vault-secrets-operator-system
spec:
  interval: 24h0m0s
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: vault-secrets-operator-system
spec:
  chart:
    spec:
      chart: vault-secrets-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault-secrets-operator-system
  interval: 12h0m0s
  values:
    defaultValueConnection:
      enabled: true
      address: "http://vault.vault.csv.cluster.local:8200"
      skipTLSVerify: false
    controller:
      manager:
        clientCache:
          persistenceModel: direct-encrypted
          storageEncryption:
            enabled: true
            mount: kubernetes
            keyName: vso-client-cache
            transitMount: demo-transit
            kubernetes:
              role: auth-role-operator
              serviceAccount: vault-secrets-operator-controller-manager
              tokenAudiences: ["vault"]
