apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: actualbudget
spec:
  entryPoints:
    - private-web
  routes:
    - match: Host(`actualbudget.warrenlayson.xyz`)
      kind: Rule
      services:
      - name: actual
        port: 5006
