---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: community-charts
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://community-charts.github.io/helm-charts
